### PR TITLE
Refactor naming and crates info

### PR DESCRIPTION
**Pull request by kubkon**
This commit:
* changes workspace crates to have a `wiggle_` prefix in names
* rename `memory` module of `wiggle-memory` crate to `runtime`
* fixes authors of all crates

### CODE REVIEW

**Comment by pchickey** [comment]
Thanks! I think this is missing the s/memory/runtime transformation, maybe that one didnt get pushed?

**Comment by kubkon** [comment]
> Thanks! I think this is missing the s/memory/runtime transformation, maybe that one didnt get pushed?

Hmm, I'm not sure what you mean. I've renamed `crates/memory/memory/` to `crates/memory/runtime/`. Unless you mean a different thing?

**Comment by pchickey** [comment]
My bad, I got confused and misread this.

I had been thinking that the new name for the `memory` crate should be `wiggle-runtime`.

The crate's `memory` module can retain that name, I think? Arrays, pointers, and GuestMemory are all "memory" as opposed to "runtime" to me.

**Comment by kubkon** [comment]
> My bad, I got confused and misread this.
> 
> I had been thinking that the new name for the `memory` crate should be `wiggle-runtime`.
> 
> The crate's `memory` module can retain that name, I think? Arrays, pointers, and GuestMemory are all "memory" as opposed to "runtime" to me.

It turns out I got it wrong in the first place, and renamed the inner module to `runtime`, rather than renaming the entire crate to `wiggle-runtime`. I've fixed it now though! :-)

**Pull request merged**
